/*
 * Energy Australia Coding Test API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Band
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-09-30T22:42:27.997+10:00[Australia/Melbourne]")
public class Band {
  @SerializedName("name")
  private String name = null;

  @SerializedName("recordLabel")
  private String recordLabel = null;

  public Band name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name!=null ? name : "";
  }

  public void setName(String name) {
    this.name = name;
  }

  public Band recordLabel(String recordLabel) {
    this.recordLabel = recordLabel;
    return this;
  }

   /**
   * Get recordLabel
   * @return recordLabel
  **/
  @Schema(description = "")
  public String getRecordLabel() {
    return recordLabel;
  }

  public void setRecordLabel(String recordLabel) {
    this.recordLabel = recordLabel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Band band = (Band) o;
    return Objects.equals(this.name, band.name) &&
        Objects.equals(this.recordLabel, band.recordLabel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, recordLabel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Band {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    recordLabel: ").append(toIndentedString(recordLabel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
